eureka:
    client:
        serviceUrl:
            defaultZone: http://localhost:5000/eureka/
server:
    port: 10000
spring:
    application:
        name: zuul
zuul:
    routes:
        api-a:
            path: /ribbon/**
            serviceId: consumerWithRibbon
        api-b:
            path: /feign/**
            serviceId: consumerWithFeign
