# see https://docs.spring.io/spring-boot/docs/2.0.9.RELEASE/reference/htmlsingle/#common-application-properties
logging:
  config: classpath:logback-spring.xml
server:
  port: 18041
  servlet:
    session:
      timeout: 7200
spring:
  zipkin:
    # zipkin server的请求地址
    bash-url: http://127.0.0.1:9411/
    # 让nacos把它当成一个URL，而不要当做服务名
    discoveryClientEnabled: false
  sleuth:
    sampler:
      # 采样的百分比
      probability: 1.0
  application:
    name: springcloud-ali-gateway
  cloud:
    gateway:
      discovery:
        locator:
          # 让gateway可以发现nacos中的微服务
          enabled: true
        # 路由数组[路由 就是指定当请求满足什么条件的时候转到哪个微服务]
        # 路由数组可以去掉，去掉后必须按约定调用才能成功，即：网关服务地址 + 微服务名 + 接口地址
        routes:
          # 当前路由的标识，要求唯一
          - id: product_route
            # 请求要转发到的地址
            # lb指的是从nacos中按照名称获取微服务，并遵循负载均衡策略
            uri: lb://service-shopproduct
            # 断言(就是路由转发要满足的条件)
            predicates:
              # 当请求路径满足Path指定的规则时，才进行路由转发
              - Path=/service-shopproduct/**
            # 过滤器，请求在传递过程中可以通过过滤器对其进行一定的修改
            filters:
              # 转发之前去掉1层路径
              - StripPrefix=1
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
      password: nacos
      username: nacos
