DROP TABLE "BHE"."T_TEST";
CREATE TABLE "BHE"."T_TEST" (
  "ID" NUMBER NOT NULL,
  "NAME" VARCHAR2(255 BYTE),
  "VALUE" NUMBER DEFAULT 0,
  "CDATE" DATE DEFAULT sysdate
)
TABLESPACE "BHE";
ALTER TABLE "BHE"."T_TEST" ADD CONSTRAINT pk_test PRIMARY KEY (ID);

DROP TABLE "BHE"."T_LOG4J";
CREATE TABLE "BHE"."T_LOG4J" (
  "LOGDATE" VARCHAR2(200 BYTE),
  "PRIORITY" VARCHAR2(100 BYTE),
  "POS" VARCHAR2(1000 BYTE),
  "THROWABLE" VARCHAR2(3000 BYTE),
  "MESSAGE" VARCHAR2(3000 BYTE),
  "THREAD" VARCHAR2(200 BYTE)
)
TABLESPACE "BHE";

