DROP TABLE "BHE"."TEST";
CREATE TABLE "BHE"."TEST" (
  "ID" NUMBER NOT NULL,
  "NAME" VARCHAR2(255 BYTE),
  "VALUE" NUMBER DEFAULT 0,
  "CDATE" DATE DEFAULT sysdate
)
TABLESPACE "BHE";
ALTER TABLE "BHE"."TEST" ADD CONSTRAINT pk_test PRIMARY KEY (ID);

DROP TABLE "BHE"."T_LOGGER";
CREATE TABLE "BHE"."T_LOGGER" (
  "MESSAGE" VARCHAR2(3000 BYTE),
  "PRIORITY" VARCHAR2(100 BYTE),
  "CLASSNAME" VARCHAR2(1000 BYTE),
  "METHOD" VARCHAR2(200 BYTE),
  "LINE" VARCHAR2(200 BYTE),
  "LOGDATE" VARCHAR2(200 BYTE),
  "THREAD" VARCHAR2(200 BYTE)
)
TABLESPACE "BHE";

