eureka:
    client:
        serviceUrl:
            defaultZone: http://localhost:5000/eureka/
server:
    port: 8000
spring:
    application:
        name: consumerWithFeign
feign:
    hystrix:
        enabled: true
