server:
    servlet:
        session:
            timeout: 1800
spring:
    redis:
        host: 127.0.0.1
        port: 6379
    session:
        redis:
            flush-mode: on-save
            namespace: spring:session
        store-type: redis
